export const styles = {
  tk: {
    backgroundColor: "#18181B",
    overflow: "hidden",
    py: 1,
  },
  tkTrack: {
    display: "flex",
    gap: "2.5rem",
    whiteSpace: "nowrap",
    animation: "tkScroll 32s linear infinite",
    "@keyframes tkScroll": {
      from: { transform: "translateX(0)" },
      to: { transform: "translateX(-50%)" },
    },
  },
  tkItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.75rem",
    fontSize: "0.68rem",
    fontWeight: 400,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.4)",
  },
  tkDot: {
    width: 3,
    height: 3,
    backgroundColor: "#C4893A",
    borderRadius: "50%",
    flexShrink: 0,
  },

  ft: {
    backgroundColor: "#FDFCFB",
    py: { xs: 6, md: 12 },
    px: { xs: 1, md: 3 },
  },
  ftInner: {
    maxWidth: "80%",
    mx: "auto",
    display: "flex",
    flexDirection: "column",
    gap: { xs: 4, md: 8 },
  },

  ftHead: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" },
    gap: { xs: 2, md: 3 },
    alignItems: "end",
  },
  ftDesc: {
    fontSize: "0.92rem",
    color: "#7A756F",
    lineHeight: 1.85,
  },
  ftGrid: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", sm: "repeat(2,1fr)" },
    gap: "1px",
    backgroundColor: "#E8E4DE",
    borderRadius: 2,
    overflow: "hidden",
  },
  ftCard: {
    backgroundColor: "#FDFCFB",
    p: { xs: 2, md: 4 },
    position: "relative",
    cursor: "default",
    transition: "background 0.22s",
    "&:hover": { backgroundColor: "#F9F7F4" },
    display: "flex",
    flexDirection: "column",
    gap: 0.9,
  },
  ftCardGhost: {
    position: "absolute",
    top: 1,
    right: 2,
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: 64,
    fontWeight: 700,
    lineHeight: 1,
    color: "rgba(196,137,58,0.08)",
    pointerEvents: "none",
    letterSpacing: "-0.04em",
  },
  ftIconBar: {
    display: "flex",
    flexDirection: "column",
    gap: 1.5,
  },

  ftIcon: {
    width: 42,
    height: 42,
    borderRadius: 1,
    backgroundColor: "rgba(196,137,58,0.09)",
    border: "1px solid rgba(196,137,58,0.22)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.15rem",
    flexShrink: 0,
  },
  ftBar: {
    width: 24,
    height: 1.5,
    backgroundColor: "#C4893A",
  },
  ftCardTitle: {
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: "1.2rem",
    fontWeight: 700,
    color: "#18181B",
    letterSpacing: "-0.015em",
  },
  ftCardDesc: {
    fontSize: "0.86rem",
    color: "#7A756F",
    lineHeight: 1.75,
  },
};
