export const styles = {
  container: {
    border: "1px solid #EBE7E0",
    borderRadius: "14px",
    p: "1.1rem",
    mb: "0.85rem",
    bgcolor: "#FFFFFF",
    boxShadow: "0 2px 6px rgba(24, 24, 27, 0.03)",
    transition: "border-color 0.2s, box-shadow 0.2s",
    "&:hover": {
      borderColor: "#D9D4CD",
      boxShadow: "0 4px 14px rgba(24, 24, 27, 0.05)",
    },
  },
  headerBox: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "0.75rem",
    mb: "0.85rem",
  },
  clientGroup: {
    display: "flex",
    gap: "0.65rem",
    alignItems: "flex-start",
    minWidth: 0,
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: "10px",
    bgcolor: "rgba(196, 137, 58, 0.12)",
    color: "#C4893A",
    fontWeight: 700,
    fontSize: "0.82rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    border: "1px solid rgba(196, 137, 58, 0.2)",
  },
  eventType: {
    fontSize: "0.92rem",
    fontWeight: 700,
    color: "#18181B",
    fontFamily: "Fraunces, Georgia, serif",
    lineHeight: 1.2,
  },
  customerName: {
    fontSize: "0.76rem",
    fontWeight: 600,
    color: "#44403C",
    mt: "0.15rem",
  },
  eventMeta: {
    fontSize: "0.72rem",
    color: "#78716C",
    mt: "0.15rem",
    display: "flex",
    alignItems: "center",
    gap: "0.3rem",
  },
  location: {
    fontSize: "0.72rem",
    color: "#A8A29E",
    mt: "0.1rem",
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
  },
  statusChip: (cfg: { bg?: string; color?: string }) => ({
    bgcolor: cfg?.bg ?? "#F5F3EF",
    color: cfg?.color ?? "#18181B",
    fontWeight: 600,
    fontSize: "0.68rem",
    height: 24,
    borderRadius: "20px",
    flexShrink: 0,
    border: `1px solid ${cfg?.color ? `${cfg.color}30` : "#E8E4DE"}`,
  }),
  divider: {
    borderColor: "#F0EDE8",
    my: "0.75rem",
  },
  footerBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.5rem",
    flexWrap: "wrap",
  },
  statsGroup: {
    display: "flex",
    gap: "1.25rem",
  },
  statLabel: {
    fontSize: "0.62rem",
    color: "#A8A29E",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    fontWeight: 600,
    mb: "0.1rem",
  },
  totalValue: {
    fontFamily: "Fraunces, Georgia, serif",
    fontSize: "0.95rem",
    fontWeight: 700,
    color: "#18181B",
  },
  earnValue: {
    fontFamily: "Fraunces, Georgia, serif",
    fontSize: "0.95rem",
    fontWeight: 700,
    color: "#16a34a",
  },
  actionsGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  callButton: {
    fontSize: "0.72rem",
    fontWeight: 600,
    color: "#FFFFFF",
    bgcolor: "#C4893A",
    borderRadius: "8px",
    px: "0.85rem",
    py: "0.35rem",
    textTransform: "none" as const,
    boxShadow: "0 2px 6px rgba(196, 137, 58, 0.25)",
    flexShrink: 0,
    "&:hover": {
      bgcolor: "#B37930",
    },
  },
  callDoneBox: {
    display: "flex",
    alignItems: "center",
    gap: "0.3rem",
    bgcolor: "rgba(22, 163, 74, 0.08)",
    border: "1px solid rgba(22, 163, 74, 0.2)",
    borderRadius: "6px",
    px: "0.55rem",
    py: "0.25rem",
  },
  callDoneText: {
    fontSize: "0.7rem",
    color: "#16a34a",
    fontWeight: 600,
  },
  detailsBtn: {
    fontSize: "0.72rem",
    fontWeight: 500,
    color: "#78716C",
    borderRadius: "8px",
    border: "1px solid #E8E4DE",
    px: "0.65rem",
    py: "0.35rem",
    textTransform: "none" as const,
    "&:hover": {
      bgcolor: "#F7F5F2",
      borderColor: "#D9D4CD",
      color: "#18181B",
    },
  },
};
